## fos_rest configuration.
---

fos_rest:
    disable_csrf_role: ROLE_ADMIN
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/', priorities: ['json', 'xml'], fallback_format: 'html' }
    routing_loader:
        default_format: json
sensio_framework_extra:
    view:
        annotations: false
    router:                    
        annotations: true   
        
twig:
#    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
