# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    app.services.user_manipulator:
        class:      AppBundle\Services\UserManipulator
        arguments:  ['@fos_user.user_manager']

    app.services.member_manipulator:
        class:      AppBundle\Services\MemberManipulator
        arguments:  ['@doctrine.orm.entity_manager']

    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments: ['@doctrine.orm.entity_manager']

    apikey_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false
        arguments: ['%api_key_name%']

    app.rest_data:
        class: AppBundle\Services\RestData
        arguments: ['@doctrine.orm.entity_manager']
