# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    app.tools.user_manipulator:
        class:      AppBundle\Tools\UserManipulator
        arguments:  ['@fos_user.user_manager']

    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments:
            em: '@doctrine.orm.entity_manager'

    apikey_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false
        arguments: 
            keyName: '%api_key_name%'
